### PR TITLE
Try to enhance UI blindly (not sure about the result)

### PR DESCRIPTION
**Pull request by kelukelu**

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you @kelukelu but there are two issues:

* Footer has now a weird aspect (because of the left menu which is not always displayed and because of the white background).
* You put back the dev section, but it should be removed.

**Comment by frankrousseau** [comment]
Oups sorry about the dev section. It's still there in production too. We should remove it. Can you take care of this?

**Comment by frankrousseau** [comment]
Only the main links should be removed, the files should be kept (some are used in the new documentation).

**Comment by kelukelu** [comment]
I couldn't install the Docs on local. So I did everything blindly, not sure if I can go to deep on that.
@frankrousseau, can you do it on your own ?

**Comment by frankrousseau** [comment]
No, I think it requires a real design work. Can you contact @jsilvestre. He's a mac user and used to work on the documentation. He may be more helpful than me about this subject.

**Comment by kelukelu** [comment]
@jsilvestre gave me a hand yesterday, but still it did not work.
@poupotte also tried to help without success.
We are definitely clueless about this issue...

**Comment by clochix** [comment]
@kelukelu any news?

**Pull request closed without merging**
