### PR TITLE
Make archlinux installation a little bit more precise

### PR DESCRIPTION
**Pull request by Niols**
After having experienced the archlinux `cozy-apache` installation, I thought a few things needed to be made more precise. Here is the corresponding PR.

What do you think about that @babolivier ?

### CODE REVIEW

**Comment by nono** [comment]
Well, @babolivier seems to be busy. The feedbacks looks valubale, I merge them. Thanks!

**Comment by babolivier** [comment]
Wow, sorry, I think my mail client messed up and I completely didn't get the notification for this one.
Seems good for me, except for the part where we `systemctl reload` the reverse proxy, as the install script restarts the said service after the configuration has taken place (https://github.com/babolivier/cozy-archlinux/blob/master/apache/cozy-apache.install#L252 & https://github.com/babolivier/cozy-archlinux/blob/master/nginx/cozy-nginx.install#L249, there's currently a typo in the nginx one, I'll correct this asap).
Anyway, thanks @Niols & @nono!

**Comment by Niols** [comment]
Hum, indeed, there is a restart. But in my case, that wasn't working, so my first hypothesis was that I needed to reload my httpd, I did it, and this worked. I'm trying to figure out why.

**Comment by babolivier** [comment]
@Niols Wasn't aware of that issue, I'll open a PR later tonight adding this in the troubleshooting part.

**Pull request merged**
