### PR TITLE
doc(troubleshooting): added some infos about VM troubles

### PR DESCRIPTION
**Pull request by sylzys**
Added some infos about what I bumped into during my first installations.
Will show in http://cozy.io/en/host/trouble-shootings.html

### CODE REVIEW

**Comment by frankrousseau** [comment]
Looks good. But can you tell that the VM you talk about is related to the development environment?

**Comment by sylzys** [comment]
Done :)

**Comment by frankrousseau** [comment]
Great, thank you!

**Comment by jsilvestre** [comment]
Thank you for the contribution, it will definitely help!
That being said, I'm feeling uneasy putting dev stuff into the "Install" section. Basically nobody will ever find it, except end users that won't understand it.

I suggest we add a troubleshooting page in the "Dev" section. It can be a new page, a dediated cookbook, or added to http://cozy.io/en/hack/cookbooks/understanding-dev-environment.html

What do you think?

**Comment by frankrousseau** [comment]
If you want to put it in the dev section, I think it should appear on the Getting Started sunsection.

**Comment by jsilvestre** [comment]
Yes, exactly what I was thinking about with "a new page" => under the "getting started" section. I think it's the best place.

**Comment by frankrousseau** [comment]
Added to the doc. Thank you both!

http://cozy.io/en/hack/getting-started/setup-environment.html

**Pull request merged**
